# Generated by Django 5.2.7 on 2025-10-23 18:02

import agendamento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('data', models.DateField()),
                ('hora', models.TimeField(validators=[agendamento.models.validate_horario])),
                ('doador', models.BooleanField(default=False)),
                ('cancelado', models.BooleanField(default=False)),
                ('token_cancelamento', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
