# Generated by Django 5.2.6 on 2025-09-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='doador',
            field=models.BooleanField(default=False),
        ),
    ]
